### ISSUE TITLE
The code doesn't work

### ISSUE THREAD

**Issue by johann83** [tval2/contextual-pruning#2]
It takes time to fix all bugs. 

However, 

After linear pruning, After activation pruning, and After embedding pruning, no numbers in metrics is changed including parameter size, sparsity, model size, perplexity and so on.

For the replication purpose, can you fix your codes? So, it works. Otherwise, the paper is not trustable.

**Comment by JusticeV452** [comment]
Hi,
Thanks for the feedback! I've cleaned up the code, and it can be tested using either example.py or run.py.

**Comment by bardia-mhd** [comment]
Hi,

I am still facing a similar issue. After linear, activation, and embedding pruning, metrics, including parameter size, sparsity, model size, perplexity, and so on, have not changed. The current model size is still the same.
